apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: juo-back
  namespace: juo
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    ##### apiVersion with match apiVersion > deployment from file deploy service (apps / deployment / api)
    apiVersion: apps/v1
    kind: Deployment
    name: juo-back
  targetCPUUtilizationPercentage: 1