apiVersion: v1
kind: Service
metadata:
  labels:
    app: juo-back
    tier: backend
  name: juo-back
  namespace: juo
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
    app: juo-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: juo-back
  name: juo-back
  namespace: juo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juo-back
  template:
    metadata:
      labels:
        app: juo-back
        tier: backend
    spec:
      containers:
      - image: git.inet.co.th:5555/iot/iot_portal_server:v1.0.2
        imagePullPolicy: Always
        name: juo-back
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      imagePullSecrets:
        - name: juosecret
      restartPolicy: Always